config/routes.rb
Rails.application.routes.draw do
  root to: "profiles#index"
  resources :profiles do
    resources :certifications
    resources :friends
    resources :hobbies
  end

  get 'info', to: 'info#index'
  get 'friendprofile', to: 'friendprofile#index'


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/certification.rb
class Certification < ApplicationRecord
  validates :name, presence: true
  validates :name, uniqueness: true
  belongs_to :profile
  has_one_attached :file
end

app/models/friend.rb
class Friend < ApplicationRecord
  belongs_to :profile
  validates :alias, presence: true
  validates :url, presence: true
  validates :alias, uniqueness: true
  validates :url, uniqueness: true
end

app/models/hobby.rb
class Hobby < ApplicationRecord
  validates :preference, presence: true
  validates :category, presence: true
  validates :preference, numericality: { only_integer: true }
  validates :name, presence: true
  validates :name, uniqueness: true
  belongs_to :profile
  enum category: [:Música, :Lectoescritura, :Aventura, :Fitness, :Coleccionismo, :Entretenimiento, :Construcción, :Gastronomía]
end

app/models/profile.rb
class Profile < ApplicationRecord
  validates :name, presence: true
  validates :lastname, presence: true
  validates :username, presence: true
  validates :email, presence: true
  validates :email, uniqueness: true
  validates :username, uniqueness: true
  validates_associated :hobbies
  validates_associated :certifications
  validates_associated :friends
  has_one_attached :image
  has_many :hobbies
  has_many :certifications
  has_many :friends
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/certifications_controller.rb
class CertificationsController < ApplicationController
  before_action :set_certification, only: [:edit, :show, :update, :destroy]
  before_action :set_profile, only: [:new, :create, :update, :destroy]

  def new
    @certification = @profile.certifications.build
  end

  def create
    @certification = Certification.new(certification_params)
    @certification = @profile.certifications.build(certification_params)
    @certification.save
    redirect_to edit_profile_path(@profile.id)
  end

  def show
  end

  def edit
  end

  def update
    @certification.update(certification_params)
    redirect_to edit_profile_path(@profile)
  end

  def destroy
    @certification.destroy
      redirect_to edit_profile_path(@profile)
  end

  private

  def certification_params
    params.require(:certification).permit(:name, :file)
  end

  def set_certification
    @certification = Certification.find(params[:id])
  end

  def set_profile
    @profile = Profile.find_by(params[:profile_id])
  end

end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :set_friend, only: [:edit, :show, :update, :destroy]
  before_action :set_profile, only: [:new, :create, :update, :destroy]

  def index
  end

  def new
    @friend = @profile.friends.build
  end

  def create
    @friend = Friend.new(friend_params)
    #@friend.profile_id = params[:@profile.id]
    @friend = @profile.friends.build(friend_params)
    @friend.save
    redirect_to edit_profile_path(@profile)
  end

  def show
  end

  def edit

  end

  def update
    @friend.update(friend_params)
    redirect_to edit_profile_path(@profile)
  end

  def destroy
    @friend.destroy
      redirect_to edit_profile_path(@profile)
  end

  private

  def friend_params
  params.require(:friend).permit(:alias, :url)
  end

  def set_friend
    @friend = Friend.find(params[:id])
  end

  def set_profile
    @profile = Profile.find_by(params[:profile_id])
  end
end

app/controllers/hobbies_controller.rb
class HobbiesController < ApplicationController
  before_action :set_hobby, only: [:edit, :show, :update, :destroy]
  before_action :set_profile, only: [:create, :update, :new, :destroy]
  def new
    @hobby = @profile.hobbies.build
  end

  def create
    @hobby = Hobby.new(hobby_params)
    @hobby = @profile.hobbies.build(hobby_params)
    @hobby.save
    redirect_to edit_profile_path(@profile)
  end

  def show
  end

  def edit
  end

  def update
    @hobby.update(hobby_params)
    redirect_to edit_profile_path(@profile)
  end

  def destroy
    @hobby.destroy
      redirect_to edit_profile_path(@profile)
  end

  private

  def hobby_params
    params.require(:hobby).permit(:name, :description, :preference, :category)
  end

  def set_hobby
    @hobby = Hobby.find_by(params[:id])
  end

  def set_profile
    @profile = Profile.find_by(params[:profile_id])
  end


end

app/controllers/info_controller.rb
class InfoController < ApplicationController
  def index
		@profile = Profile.last
	end
	
	private

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
	before_action :set_profile, only: [:edit, :update, :destroy]

	def new
		@profile = Profile.new
	end

	def create
		@profile = Profile.new(profile_params)
		if @profile.save
			@profile.image.attach(io: File.open(Rails.root.join("app", "assets", "images", "default.png")), filename: 'default.png' , content_type: "image/png")
			redirect_to info_path(@profile), notice: "Se ha creado tu perfil!"
		else
			redirect_to new_profile_path
		end
	end

def index
	if !params[:url]
		@profile = Profile.first
		if !@profile.nil?
			@profile = {'profile' => {'firstname' => @profile.name, 'lastname' => @profile.lastname, 'birthdate' => @profile.birthdate, 'username' => @profile.username, 'subtitle' => @profile.subtitle, 'email' => @profile.email, 'bio' => @profile.biography, 'hobbies' => @profile.hobbies, 'certificates' => @profile.certifications, 'friends' => @profile.friends, 'image' => @profile.image, 'id' => @profile.id}}
		else
			redirect_to new_profile_path
		end
	else
		@hash = RestClient.get("#{params[:url]}")
		@profile = JSON.parse(@hash)
		puts @profile
	end
end

	def show
		@profile = Profile.find(params[:id])
		respond_to do |format|
			if !@profile.nil?
				format.html
				format.json { render json: @profile}
			else
				format.html {redirect_to new_profile_path}
				format.json { render json: @profile.errors, status: :unprocessable_entity}
			end
		end
	end

	def edit
	end

	def update
		if @profile.update(profile_params)
			redirect_to profiles_path
		else
			render :edit
		end
	end

  private

    def profile_params
			params.require(:profile).permit(:name, :lastname, :subtitle, :email, :username, :biography, :birthdate, :image)
  	end

		def set_profile
			@profile = Profile.find(params[:id])
		end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/certifications_helper.rb
module CertificationsHelper
end

app/helpers/friend_profiles_helper.rb
module FriendProfilesHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/hobbies_helper.rb
module HobbiesHelper
end

app/helpers/info_helper.rb
module InfoHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/certifications/edit.html.haml
%h1 Modifica tu certificación

= form_with(model: [:profile, @certification], local: true) do |form|
	.field
		= form.label :name, "Nombre"
		= form.text_field :name
	.field
		= form.label :file, "Nombre"
		= form.file_field :file
	.actions
		= form.submit("GUARDAR")

app/views/certifications/new.html.haml
%h1 Nueva Certificación

= form_with(model: [@profile, @certification], local: true) do |form|
	.field
		= form.label :name, "Nombre"
		= form.text_field :name
	.field
		= form.file_field :file
	.actions
		= form.submit("CREAR")

app/views/friend_profiles/index.html.haml
%p
  %b Name:
  = @profile[firstname]

app/views/friends/edit.html.haml
%h1 Modifica tu amigo

= form_with(model: [:profile, @friend], local: true) do |form|
	.field
		= form.label :alias, "Alias"
		= form.text_field :alias
	.field
		= form.label :url, "URL"
		= form.text_field :url
	.actions
		= form.submit("GUARDAR")

app/views/friends/index.html.haml
%p
  %b Name:
  = @profile[firstname]

app/views/friends/new.html.haml
%h1 Nuevo Amigo

= form_with(model: [@profile, @friend], local: true) do |form|
  .field
    = form.label :alias, "Alias"
    = form.text_field :alias
  .field
    = form.label :url, "URL"
    = form.text_field :url
  .actions
    = form.submit("CREAR")

app/views/hobbies/edit.html.haml
%h1 Modifica tu Hobby

= form_with(model: [:profile , @hobby], local: true) do |form|
  .field
    = form.label :name, "Nombre"
    = form.text_field :name
  .field
    = form.label :description, "Descripción"
    = form.text_field :description
  .field 
    = form.label :preference, "Preferencia"
    = form.text_field :preference
  .field
    = form.label :category, "Categoria"
    = form.select :category, Hobby.categories.keys.map { |category| [category.titleize, category]}, include_blank: true
  .actions
    = form.submit("GUARDAR")

app/views/hobbies/new.html.haml
%h1 Nuevo Hobby

= form_with(model: [@profile ,@hobby], local: true) do |form|
  .field
    = form.label :name, "Nombre"
    = form.text_field :name
  .field
    = form.label :description, "Descripción"
    = form.text_field :description
  .field
    = form.label :preference, "Preferencia"
    = form.text_field :preference
  .field
    = form.label :category, "Categoria"
    = form.select :category, Hobby.categories.keys.map { |category| [category.titleize, category]}, include_blank: true
  .actions
    = form.submit("CREAR")

app/views/info/index.html.haml
.info
	.row.mt-5
		.col.text-center
			%h2 Date a conocer
	.row.mt-2
		.col.text-center
			%h2 Agrega información adicional (fotos, hobbies, certificaciones, amigos)
	.row.mt-2
		.col-2.offset-4.text-center
			= link_to 'Ir al perfil', profiles_path, class: 'btn btn-primary'
		.col-2.text-center
			= link_to 'Editar perfil', edit_profile_path(@profile), class: 'btn btn-primary'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title HackProfile
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = yield

app/views/profiles/edit.html.haml
.row.mt-5
	.col.text-center
		%h2 Modifica tu perfil
.row
	.col-6.offset-3.editform
		.row.mt-2
			.col.text-center
				%h5 Datos básicos
		= form_with(model: @profile, local: true) do |form|
			.field
				.row.mt-2
					.col-4.mt-2.offset-1
						= form.label :name, "Nombre:"
					.col-4.offset-1.mt-1
						= form.text_field :name
			.field
				.row
					.col-4.mt-2.offset-1
						= form.label :lastname, "Apellido:"
					.col-4.offset-1.mt-1
						= form.text_field :lastname
			.field
				.row
					.col-4.mt-2.offset-1
						= form.label :subtitle, "Ocupación:"
					.col-4.offset-1.mt-1
						= form.text_field :subtitle
			.field
				.row
					.col-4.mt-2.offset-1
						= form.label :email, "Correo:"
					.col-4.offset-1.mt-1
						= form.text_field :email
			.field
				.row
					.col-4.mt-2.offset-1
						= form.label :username, "Nombre de Usuario:"
					.col-4.offset-1.mt-1
						= form.text_field :username
				.field
				.row
					.col-4.mt-4.offset-1
						= form.label :biography, "Biografía:"
					.col-4.offset-1.mt-1
						= form.text_area :biography
			.field
				.row
					.col-4.mt-2.offset-1
						= form.label :birthdate, "Fecha de Nacimiento:"
					.col-4.offset-1.mt-1
						= form.date_field :birthdate
			.field
				.row
					.col-4.offset-1.mt-3
						= form.label :image, "Foto de Perfil:"
					.col-4.offset-1.mt-2
						.image
							= image_tag @profile.image, :class => "foto"
				.row
					.col.offset-2
						= form.file_field :image
			.actions
				.row.mt-4.mb-4
					.col.text-center
						= form.submit("Guardar",:class => "btn btn-primary")

.row.mt-2
	.col-6.offset-3
		.row
			.col.mt-2.text-center
				%h5 Hobbies
		%table
			%thead
				%tr
					%th Nombre
					%th Descripción
					%th Preferencia
					%th Categoría
					%th{colspan: "2"}
			%tbody
				- @profile.hobbies.each do |hobby|
					%tr
						%td= hobby.name
						%td= hobby.description
						%td= hobby.preference
						%td= hobby.category
						%td= link_to 'Editar', edit_profile_hobby_path(@profile.id, hobby.id)
						%td= link_to 'Eliminar', profile_hobby_path(@profile.id, hobby.id), method: :delete, data: { confirm: 'Estas seguro?' }
		.row.mt-2.text-center
			.col
				=link_to 'Nuevo Hobby', new_profile_hobby_path(@profile.id), class: 'btn btn-primary'




.row.mt-2.ml-1
	.col-6.offset-3
		.row
			.col.mt-2.text-center
				%h5 Certificaciones
		%table
			%thead
				%tr
					%th Nombre
					%th Archivo
					%th{colspan: "2"}
			%tbody
				- @profile.certifications.each do |certification|
					%tr
						%td= certification.name
						%td= certification.file.filename
						%td= link_to 'Editar', edit_profile_certification_path(@profile.id, certification.id)
						%td= link_to 'Eliminar', profile_certification_path(@profile.id, certification.id), method: :delete, data: { confirm: 'Estas seguro?' }
		.row.mt-2.text-center
			.col
				=link_to 'Nueva certificación', new_profile_certification_path(@profile.id), class: 'btn btn-primary'

.row.mt-2.ml-5
	.col-6.offset-3
		.row
			.col.mt-2.text-center.mr-5
				%h5 Amigos
		%table
			%thead
				%tr
					%th Alias
					%th URL
					%th{colspan: "2"}
			%tbody
				- @profile.friends.each do |friend|
					%tr
						%td= friend.alias
						%td= friend.url
						%td= link_to 'Editar', edit_profile_friend_path(@profile.id, friend.id)
						%td= link_to 'Eliminar', profile_friend_path(@profile.id, friend.id), method: :delete, data: { confrim: 'Estas seguro?' }
		.row.mt-2.text-center.mr-5
			.col
				=link_to 'Agregar', new_profile_friend_path(@profile.id), class: 'btn btn-primary'
.row.mt-4
	.col.offset-1
		=link_to 'Ir a tu perfil', root_path, class: 'btn btn-primary'

app/views/profiles/index.html.haml
-# %p#notice= notice
.headercontainer.col-10.offset-1
  .row
    .col-4.text-center.offset-4.mt-3
      %h1
        = @profile['profile']['firstname'] + " #{@profile['profile']['lastname']}"
  .row
    .col-4.text-center.offset-4.mb-2
      %h6
        = @profile['profile']['subtitle']

-# %p
-#   %b Nombre de usuario:
-#   = @profile['profile']['username']

.infocontainer.col-10.offset-1
  .row
    .col-11.offset-1.mt-2
      %h5 Información Básica

.basicdatacontainer.col-10.offset-1
  .row.mt-4
    .col-8.offset-1
      %p
        = @profile['profile']['bio']
      %p
        %b Edad:
        = @profile['profile']['birthdate']
      %p
        %b Correo Electrónico:
        = @profile['profile']['email']
    .col-2.offset-1
      .image 
        %img= image_tag @profile['profile']['image'], :class => "foto"

.infocontainer.col-10.offset-1
  .row
    .col-11.offset-1.mt-2
      %h5 Mis Hobbies
.hobbiescontainer.col-10.offset-1
  .row.mb-3
    - if @profile['profile']['hobbies'].present?
      - @profile['profile']['hobbies'].each do |hobby|
        .hobby.col-5.offset-1.mt-3
          .row.mt-2
            .col
              %strong= hobby.name
            .col
              %p= hobby.category
          .row
            .col
              %p= hobby.description
          .row
            .col
              = hobby.preference
    - else
      .col-5.offset-1.mt-3
        %p Edite su perfil para añadir hobbies  

.infocontainer.col-10.offset-1
  .row
    .col-11.offset-1.mt-2
      %h5 Mis Certificaciones
.certificatescontainer.col-10.offset-1.mb-2
  .row
    .col
      %ul 
      - if @profile['profile']['certificates'].present?
        - @profile['profile']['certificates'].each do |certificate|
          .row
            .col-5.offset-1.mt-2
              %li
                = certificate.name
                = link_to 'Descargar', url_for(certificate.file)
      - else
        .col-5.offset-1.mt-3
          %p Edite su perfil para añadir certificados
.infocontainer.col-10.offset-1
  .row
    .col-11.offset-1.mt-2
      %h5 Contactos
.friendscontainer.col-10.offset-1
  .row
    - if @profile['profile']['friends'].present?
      - @profile['profile']['friends'].each do |friend|
        .friend.col-3.offset-1.mt-4
          .row
            .col
              .image
                %img= image_tag @profile['profile']['image'], :class => "foto"
          .row.mt-2
            .col.text-center
              = link_to "#{friend.alias}", "http://localhost:3000/?url=#{friend.url}", class: 'link'
    - else
      .col-5.offset-1.mt-3
        %p Edite su perfil para añadir amigos 
.infocontainer.col-10.offset-1.mb-2.mt-2
  .row.mb-2.mt-3
    .col-8.offset-1.mt-1
      %h6 Developed by: Anderson Sánchez 2018
    .col-2.offset-1.mb-1
      = link_to 'Editar Perfil', edit_profile_path(@profile['profile']['id']), class: 'btn btn-primary btn-sm'

app/views/profiles/index.html_unprofile.haml
%p#notice= notice
%p
  %b Name:
  = @profile[:profile][:firstname]
%p
  %b Lastname:
  = @profile[:profile][:lastname]
%p
  %b Ocupación:
  = @profile[:profile][:subtitle]
%p
  %b Correo Electrónico:
  = @profile[:profile][:email]
%p
  %b Nombre de usuario:
  = @profile[:profile][:username]
%p
  %b Biografía:
  = @profile[:profile][:bio]
%p
  %b Fecha de Nacimiento:
  = @profile[:profile][:birthdate]
.image
  = image_tag @profile.image
%ul Mis Hobbies
- @profile.hobbies.each do |hobby|
  %li
    = hobby.name
    = hobby.category
  %br
  %li
    = hobby.description
  %br
  %li
    = hobby.preference
  %br
%ul Mis Certificaciones
- @profile.certifications.each do |certification|
  %li
    = certification.name
    = link_to 'Descargar', url_for(certification.file)
  %br
%h1 Contactos
- @profile.friends.each do |friend|
  .frienddiv
    = link_to "#{friend.alias}", "http://localhost:3000/?url=#{friend.url}"
%br/
= link_to 'Editar Perfil', edit_profile_path(@profile)

app/views/profiles/new.html.haml
.row.mt-5
	.col.text-center
		%h2 No se encontró tu perfil.
.row
	.col-4.offset-4.text-center
		= render 'shared/modal'

app/views/profiles/show.html.haml
%p#notice= notice
%p
  %b Name:
  = @profile.name
%p
  %b Lastname:
  = @profile.lastname
%p
  %b Ocupación:
  = @profile.subtitle
%p
  %b Correo Electrónico:
  = @profile.email
%p
  %b Nombre de usuario:
  = @profile.username
%p
  %b Biografía:
  = @profile.biography
%p
  %b Fecha de Nacimiento:
  = @profile.birthdate


= link_to 'Edit', edit_profile_path(@profile)

app/views/shared/_modal.html.haml
%button.btn.btn-primary{ data: { target: '#modal', toggle: 'modal' } }
  .row
    .col
      Crear perfil

#modal.modal.fade
  .modal-dialog
    .modal-content
      .modal-header
        .row
          .col-8.text-right
            %h4.modal-title
              Datos básicos
          .col-2.offset-2
            %button.close{ 'data-dismiss': 'modal' }
              x
          .modal-body
            = form_with(model: @profile, local: true) do |form|
              .field
                .row
                  .col-4.offset-1
                    = form.label :name, "Nombre:"
                  .col-4.offset-1
                    = form.text_field :name                    
              .field
                .row.mt-1
                  .col-4.offset-1
                    = form.label :lastname, "Apellido:"
                  .col-4.offset-1
                    = form.text_field :lastname
              .field
                .row.mt-1
                  .col-4.offset-1
                    = form.label :subtitle, "Ocupación:"
                  .col-4.offset-1
                    = form.text_field :subtitle
              .field
                .row.mt-1
                  .col-4.offset-1
                    = form.label :email, "Correo:"
                  .col-4.offset-1
                    = form.text_field :email
              .field
                .row.mt-1
                  .col-5.offset-1
                    = form.label :username, "Nombre de Usuario:"
                  .col-3
                    = form.text_field :username
              .field
                .row.mt-1
                  .col-4.offset-1
                    = form.label :biography, "Biografía:"
                  .col-4.offset-1
                    = form.text_area :biography
              .field
                .row.mt-1
                  .col-5.offset-1
                    = form.label :birthdate, "Fecha de Nacimiento:"
                  .col-3
                    = form.date_field :birthdate
              .actions
                .row.mt-4
                  .col.text-center
                    = form.submit("CREAR",:class => "btn btn-primary")